=== Kubernetes

You can find all the deployment files in the link:https://github.com/spoud/kafka-cost-control/tree/master/deployment[deployment] folder. This folder use link:https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/[Kustomize] to simplify the deployment of multiple instances with some variations.

The kubernetes deployment is in two parts. One part is the *kafka cost control software* (processing and UI) and the other part is the *kafka metric scrapper*. You may have multiple kafka metric scrapper deployment (one per kafka cluster for example), but you should need only one kafka cost control deployment.

==== Kafka metric scraper

This part will be responsible to scrape kafka for relevant metrics. Depending on what metrics you want to provide you will need a user with read access to kafka metric but also kafka admin client. Read permission is enough ! You don't need a user with write permission.

This documentation will assume that you use the `dev/` folder, but you can configure as much Kustomize folders as you want. The `dev/` folder is a good starting point if you have confluent cluster running.

Copy the environment sample file:
[,shell]
----
cd deployment/kafka-metric-scrapper/dev
cp .env.sample .env
vi .env
----
Edit the environment file with the correct output topic, endpoints and credentials.

Be sure to edit the *namespace* in the link:https://github.com/spoud/kafka-cost-control/tree/master/deployment/kafka-metric-scrapper/dev/kustomization.yaml[kustomization.yaml] file.

Deploy the dev environment using kubectl

[,shell]
----
cd /deployment/kafka-metric-scrapper
kubectl apply -k dev
----

Wait for the deployment to finish and check the output topic for metrics. You should receive new data every minute.

==== Kafka cost control

For this part we will deploy the kafka stream application that is responsible to enrich the metrics (it stores them in its built-in DuckDB database, see <<section-metric-storage>>) and the UI to browse costs and define prices and contexts.

The link:https://github.com/spoud/kafka-cost-control/tree/master/deployment/kafka-cost-control/base[base] folder contains the manifests. Create your own Kustomize overlay next to it, for example `deployment/kafka-cost-control/my-env/kustomization.yaml`:

[source,yaml]
----
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

namespace: kafka-cost-control

# the base leaves the Ingress hosts as TO_BE_DEFINED_BY_OVERRIDE, which Kubernetes rejects
patches:
  - target:
      kind: Ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: kcc.example.com

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: kafka-cost-control-secret
  envs:
  - .env
----

Put your credentials in a `.env` file in the same folder:

[source,shell]
----
KAFKA_BOOTSTRAP_SERVERS=cluster.region.confluent.cloud:9092
CLUSTER_API_KEY=kafka-api-key
CLUSTER_API_SECRET=kafka-api-secret

KAFKA_SCHEMA_REGISTRY_URL=https://cluster.region.confluent.cloud
SCHEMA_REGISTRY_API_KEY=schema-registry-api-key
SCHEMA_REGISTRY_API_SECRET=schema-registry-api-secret

# Comma separated list of topics that contain raw metrics from telegraf
CC_TOPICS_RAW_DATA=metrics-raw-telegraf-dev

# Admin password
CC_ADMIN_PASSWORD=admin
----

Replace `kcc.example.com` with your own host. It is used by both the UI and the aggregator's `/graphql` endpoint.

Deploy the application using kubectl

[,shell]
----
cd deployment/kafka-cost-control
kubectl apply -k my-env
----

==== Helm Chart (Strimzi only)

If your Kafka cluster is managed by the Strimzi operators, you can use the provided Helm chart (under `helm/kcc-strimzi`) to deploy
Cost Control with all the required components (Telegraf, Aggregator, UI) as well as all the required
users and topics. The Helm chart still assumes that you already have a Schema Registry deployed.
See the relevant README file for more information.

A component that is special to the Strimzi deployment is the Context Operator.
This operator detects `KafkaUser` resources with a specific annotation and automatically creates
a corresponding `Context` in Cost Control. This allows you to manage your contexts directly from Kubernetes.
See the README in `strimzi-operator` for more information.
