=== Grafana

Go to your grafana dashboard (you should have configured the host in the deployment). The default credentials are `admin:admin`. You will be asked to create a new password.

==== Database connection
Go to the administration page and search for the plugin called `PostgreSQL`. It should normally be already installed, if not install it. You can then click on `add new data source`.


[options="header"]
|===
| Field | Value | Info

| Name | grafana-postgresql-datasource | _should be the default_
| Host URL | timescaledb-service:5432 | _Kubernetes service for the database_
| Database Name | postgres | _this is the default if you didn't change it_
| Username | postgres | _this is the default if you didn't change it_
| Password | postgres | _this is the password you created in the `.env` file of the deployment_
| TLS/SSL Mode | disabled | _unless you configured it_
| TimescaleDB | on | _this will improve performance_

|===

You  can keep the rest of the value as default.

TODO import dashboard
