kafka:
  application:
    id: kafka-cost-control-scraper
  bootstrap:
    servers: localhost:9092
  schema:
    registry:
      url: http://localhost:8081
quarkus:
  kafka:
    snappy:
      enabled: true
  native:
    container-build: true
  rest-client:
    schema-registry-api:
      url: ${kafka.schema.registry.url}
  devservices:
    enabled: false
  micrometer:
    binder:
      vertx:
        enabled: false
      netty:
        enabled: false
      http-client:
        enabled: false
      jvm: false
      system: false
  scheduler:
    start-mode: forced
cc:
  scrape:
    sr:
      interval-seconds: 600
    kafka:
      interval-seconds: 600
