# Telegraf on Confluent's metrics export plus the kafka-scraper, see ../confluent-scraper.
kind: Kustomization
resources:
  - ../confluent-scraper

namespace: kafka-cost-control-scraper

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: telegraf-secret
    envs:
      - .env-telegraf
  - name: kafka-cost-control-scraper-secret
    envs:
      - .env-scraper
