kind: Kustomization
resources:
  - ../base
  - scraper.yaml

namespace: kafka-cost-control-mgb-qual

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: telegraf-secret
    envs:
      - .env-telegraf
  - name: kafka-cost-control-scraper-secret
    envs:
      - .env-scraper

configMapGenerator:
  - name: telegraf-config
    files:
      - telegraf-config.toml
