# Global tags can be specified here in key="value" format.
[global_tags]
    env = "${ENVIRONMENT_NAME}"

[agent]
    interval = "60s"
    round_interval = true
    metric_batch_size = 1000
    metric_buffer_limit = 10000
    collection_jitter = "0s"
    flush_interval = "10s"
    flush_jitter = "0s"
    precision = "0s"
    hostname = "confluent.cloud"
    omit_hostname = false

[[inputs.prometheus]]
    urls = ${INPUT_URLS}
    username = "${INPUT_CONFLUENT_METRICS_API_KEY}"
    password = "${INPUT_CONFLUENT_METRICS_API_SECRET}"
    [inputs.prometheus.tags]
        source="confluent-metric-api"

[[inputs.prometheus]]
    urls = ["http://kafka-cost-control-scraper-service:8080/q/metrics"]
    [inputs.prometheus.tags]
        source="kafka-metric-scrapper"

[[outputs.kafka]]
    brokers = ${OUTPUT_BROKERS}
    topic = ${OUTPUT_TOPIC}
    client_id = "telegraf-scrapper"
    routing_tag = "host"
    idempotent_writes = true
    max_retry = 3
    enable_tls = true
    sasl_username = "${OUTPUT_KAFKA_SASL_USERNAME}"
    sasl_password = "${OUTPUT_KAFKA_SASL_PASSWORD}"
    sasl_mechanism = "PLAIN"
    data_format = "json"
