{
 "title": "Kafka Costs by Application",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(principal)" } }
  ]
 },
 "panels": [
  {
   "title": "Application Topic Sizes",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time (kcc_kafka_log_log_size{principal=\"$application\"}[2m])) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentage of total consume traffic",
   "type": "stat",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(kcc_kafka_server_brokertopicmetrics_bytesout_total{principal=\"$application\"}[2m])) / sum(max_over_time(kcc_kafka_server_brokertopicmetrics_bytesout_total{principal!=\"unknown\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentage of total storage usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(kcc_kafka_log_log_size{principal=\"$application\"}[2m])) / sum(max_over_time(kcc_kafka_log_log_size{principal!=\"unknown\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentage of total produce traffic",
   "type": "stat",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(kcc_kafka_server_brokertopicmetrics_bytesin_total{principal=\"$application\"}[2m])) / sum(max_over_time(kcc_kafka_server_brokertopicmetrics_bytesin_total{principal!=\"unknown\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}