apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kcc
  name: kcc
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    k8s-app: ctf-kcc-kafka-cost-control
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: prometheus
  name: prometheus
spec:
  volumeClaimTemplates:
  - spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 4Gi
    metadata:
      name: data
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-config
      containers:
      - image: prom/prometheus:latest
        name: prometheus
        volumeMounts:
        - mountPath: /etc/prometheus
          name: config-volume
          readOnly: true
        - mountPath: /prometheus
          name: data
        ports:
        - containerPort: 9090
        resources: {}
---
apiVersion: v1
data:
  prometheus.yml: |-
    global:

    scrape_configs:
      - job_name: 'kcc'
        scrape_interval: 30s
        metrics_path: /q/metrics
        static_configs:
          - targets: [ 'kcc:8080' ]
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: prometheus
  name: prometheus
spec:
  ports:
  - name: 9090-9090
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
  type: ClusterIP
