ifndef::imagesdir[:imagesdir: ../images]

[[section-system-scope-and-context]]
== System Scope and Context

Kafka Cost Control is a standalone application that needs to integrate into an existing IT landscape.

////
.Contents
System scope and context - as the name suggests - delimits your system (i.e. your scope) from all its communication partners
(neighboring systems and users, i.e. the context of your system). It thereby specifies the external interfaces.

If necessary, differentiate the business context (domain specific inputs and outputs) from the technical context (channels, protocols, hardware).

.Motivation
The domain interfaces and technical interfaces to communication partners are among your system's most critical aspects. Make sure that you completely understand them.

.Form
Various options:

* Context diagrams
* Lists of communication partners and their interfaces.


.Further Information

See https://docs.arc42.org/section-3/[Context and Scope] in the arc42 documentation.

////

[plantuml, target=context-diagram, format=svg]
....
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
LAYOUT_WITH_LEGEND()
title System Context diagram for Kafka Cost Control

Person(developer, "App Developer", "Developer of applications that use the Kafka infrastructure")
Person(controller, "Controller", "Person in charge of monitoring and planning platform costs")
Person(admin, "Admin", "Kafka Platform administrator")

System(kcc, "Kafka Cost Control", "Cost monitoring application")
System_Ext(kafka, "Kafka Platform", "On-prem or SaaS Kafka infrastructure.")
System_Ext(analytics, "Analytics Tool", "External dashboard or analytics tool present in the company")

Rel(developer, kcc, "view\n app costs")
Rel(controller, kcc, "create \nend-of-month\n reports")
Rel(admin, kcc, "configure\n pricing rules")
Rel(kafka, kcc, "raw usage\n metrics")
Rel(kcc, analytics, "aggregated usage\n metrics")
@enduml
....



