ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
=== Solution Strategy
////
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape system architecture. It includes

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the foundation for many other detailed decisions or implementation rules.

.Form
Keep the explanations of such key decisions short.

Motivate what was decided and why it was decided that way,
based upon problem statement, quality goals and key constraints.
Refer to details in the following sections.


.Further Information

See https://docs.arc42.org/section-4/[Solution Strategy] in the arc42 documentation.

////

==== Used Technologies


|===
|Technology | Reason

| Telegraf
a|
* Used for scraping metrics from data sources like Prometheus agents or Confluent Cloud API.
* Versatile and lightweight tool that can be run in all environments.
* supports Kafka

| Kafka
| for storing metrics, context info and pricing rules, reduces number of solution dependencies

|===






