ifndef::imagesdir[:imagesdir: ../images]

[[section-deployment-view]]


=== Deployment View

[plantuml,target=deployment-view,format=svg]
....
@startuml
left to right direction


cloud Confluent{
    component "KafkaAdminAPI"
    component "MetricsEndpoint"
}

frame MetricScrapper as "Metric Scrapper part" {
    component "Telegraf-confluent-metric"
    component "MetricAPIReader"
    component "Telegraf-kafka-admin"

    "Telegraf-kafka-admin" -up-> "MetricAPIReader": scrape
}

frame KafkaCostControl {
    component MetricsProcessor
    component KafkaConnect
    component ConfigurationUI
    component Dashboard
    database MetricDatabase

    "KafkaConnect" --> "MetricDatabase"
    "ConfigurationUI" -up-> "MetricsProcessor": Graphql
    "Dashboard" -up-> "MetricDatabase"
}

queue "raw-metrics-confluent"
queue "raw-metrics-admin-api"
queue "aggregated-metrics"

actor "User"

"Telegraf-confluent-metric" -up-> "MetricsEndpoint": scrape
"MetricAPIReader" -up-> "KafkaAdminAPI": pool

"Telegraf-confluent-metric" -down-> "raw-metrics-confluent": publish
"Telegraf-kafka-admin" -down-> "raw-metrics-admin-api": publish

"raw-metrics-confluent" --> "MetricsProcessor": consume
"raw-metrics-admin-api" --> "MetricsProcessor": consume

"MetricsProcessor" --> "aggregated-metrics": publish

"aggregated-metrics" --> "KafkaConnect": sink

"User" -up-> "ConfigurationUI": use
"User" -up-> "Dashboard": use

@enduml
....


