# loaded from /etc/telegraf/telegraf.d next to telegraf.conf
[[inputs.prometheus]]
    urls = ["http://kafka-cost-control-scraper-service:8080/q/metrics"]
    namepass = ["kafka_topic_partition_count", "kafka_topic_schema_count"]
    [inputs.prometheus.tags]
        source="kafka-metric-scrapper"
