
# Default values for telegraf.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Used as a tag in all scraped metrics
env: dev
debug: false

topics:
  rawMetrics:
    partitions: 3
    # default: 90 days retention
    retentionMs: "7776000000"

strimzi:
  clusterName: my-cluster
  bootstrapServer: my-cluster-kafka-bootstrap:9094
  # "scram-sha-512" or "tls" or "none"
  auth: scram-sha-512
