=== Context data

Context data are a way to attach a context (attributes basically) to a kafka item (topic, principal, ...). Basically define a set of key/values for an item that match a regex. It is possible that one item match multiple regex (and thus multiple context), but in this case you have to be careful to not have conflicting key/values.

You can have as much key/values as you want. They will be used to sum up prices in the dashboard. It is therefor important that you have at least one key/value that defined the cost unit or organization unit. For example: `organzation_unit=department1`.

The context data are stored in kafka in a compacted topic. The key is free for the user to choose.

==== Listing existing context data

===== From the UI

Go to the tab _Context Data_ in the UI. You should see all the context with their validity time, type, regex and context key/values.

If you are signed in, you can use the context tester via the button _test context data_ to check what context key/values currently apply to your topic or principal.

===== Using Graphql

[source,graphql]
----
query getContextData {
  contextData {
    id
    creationTime
    validFrom
    validUntil
    entityType
    regex
    context {
      key
      value
    }
  }
}
----

==== Setting context data

If you want to create a new context, you can omit the id if you want. If no id is set, the API will generate one for you using a UUID.
If you use an id that is not yet in the system, this means you're creating a new context item.

===== From the UI
In the Context Data tab via the button _Add context data_. You need to be signed in for the button to be visible.

===== Using Graphql
[source,graphql]
----
mutation saveContextData {
  saveContextData(
    request: {id: "323b603d-5b5f-48d2-84fc-4e784e942289", entityType: TOPIC, regex: ".*collaboration", context: [{key: "app", value: "agoora"}, {key: "cost-unit", value: "spoud"}, {key: "domain", value: "collaboration"}]}
  ) {
    id
    creationTime
    entityType
    regex
    context {
      key
      value
    }
  }
}
----

==== Removing context data

===== From the UI
_Not available yet._

===== Using Graphql
[source,graphql]
----
mutation deleteContextData {
  deleteContextData(request: {id: "323b603d-5b5f-48d2-84fc-4e784e942289"}) {
    id
    creationTime
    entityType
    regex
    context {
      key
      value
    }
  }
}
----
