=== Configuring your cost control application

Your cost control instance can be configured either by setting environment variables,
or (if you are using one of the provided container images) by mounting an `application.properties` file at
`/deployments/config/application.properties`:

```
# inside your application.properties
quarkus.profile=ccloud
```

==== Configuring aggregation types

In cost control, each metric is associated with an aggregation type. The aggregation type determines how multiple measurements
within a time window are combined to produce a single value. Possible aggregation types are `SUM` and `MAX`.
If no aggregation type is specified for a metric, then `SUM` will be used.
To specify an aggregation type for a metric, add a line to your `application.properties` file like this:

```
# inside your application.properties
cc.metrics.aggregations.<metric-name>=max
```

For example, to aggregate retained byte measurements using the `MAX` aggregation type, add the following line to your `application.properties` file:

```
cc.metrics.aggregations.confluent_kafka_server_retained_bytes=max
```

Note that these settings may only be set in an `application.properties` file, and not via environment variables.
This is due to the fact that Quarkus cannot unambiguously map environment variable names to property names if said
property names contain user-defined parts (like `confluent_kafka_server_retained_bytes` in the example above).
For more information, see https://quarkus.io/guides/config-reference#environment-variables[the relevant section of the Quarkus documentation].

==== Configuring transformations

Currently, there is one kind of transformation that can be added to the metrics processing pipeline: `splitTopicMetricAmongPrincipals`.
This transformation is configured by supplying a map of metric names to context keys in application.properties. For example:

```properties
cc.metrics.transformations.splitMetricAmongPrincipals={bytesin:'writers',bytesout:'readers'}
```

This will expect `bytesin` metrics to have a `writers` key in their context, which should be a comma-separated list of principals (e.g. applications, teams, ...)
that can write to this topic. When a `bytesin` metric for any topic is encountered, the metric will be replaced with `n` metrics (where `n` is the length of the `writers` list
in that metric's context). The name of the topic will be moved into that metric's context under the `topic` key and the name of a principal from the `writers`
list will move into the metric's `name` field. The value of each generated metric will be the value of the original metric divided by `n`.

In effect this takes a single metric that says "90 kb have been written to topic ABC by writers X,Y,Z" and transforms it into 3 metrics:

- Principal X wrote 30 kb to topic ABC
- Principal Y wrote 30 kb to topic ABC
- Principal Z wrote 30 kb to topic ABC

The advantage over the original metric is that each such transformed metric will be put into its own database row, which will make it easier to aggregate by principal
(e.g. answer questions like "how much did principal X produce in the past month"). This type of transformation is especially relevant when doing cost control based on vanilla
Kafka broker metrics (as is the case in Strimzi deployments, for example), because here only topic-level metrics are generated natively. This transformation allows to turn
these topic-focused metrics into principal-focused ones.

Some metrics that are configured this way may not have a matching context key in the context. To handle such cases, cost control offers three different strategies
that can be enabled by setting the `cc.metrics.transformations.config.splitMetricAmongPrincipals.missingKeyHandling` property in `application.properties`:

- `ASSIGN_TO_FALLBACK`: The metric will be handled as if the context key existed and contained a single principal name. This fallback principal name is set to "unknown" per default but can be changed
  by setting the `metrics.transformations.config.splitMetricAmongPrincipals.fallbackPrincipal` property in `application.properties`.
- `DROP`: The metric will not be forwarded downstream and will be dropped.
- `PASS_THROUGH`: The metric will be passed downstream without any changes. This is the default behavior.

Note that `cc.metrics.transformations.config.splitMetricAmongPrincipals.missingKeyHandling` is expected to be a map of metric names to one of the above strategies.
For example:

```properties
cc.metrics.transformations.config.splitMetricAmongPrincipals.missingKeyHandling={bytesin:'ASSIGN_TO_FALLBACK',bytesout:'DROP'}
```

If no strategy is specified for a metric, then `ASSIGN_TO_FALLBACK` will be used.
