== Reprocess

Reprocessing should only be used when you made a mistake, fixed it and want to reprocess the raw data. Reprocessing will induce a lag, meaning data will not be live for a little while. Depending on how much data you want to reprocess this can take minutes or hours. So be sure to know what you are doing. After the reprocessing is done, the data will be live again. Reprocessing will *NOT* lose data. They will just take a bit of time to appear live again.

Be aware that in the reprocessing action may take a while to complete (usually about 1 min). This is why you should be patient with the request.

The process is as follows:

  * use request reprocessing
  * KafkaCostControl MetricProcess kafka stream application will stop
  * Wait for all consumers to stop and for kafka to release the consumer group (this may take time)
  * KafkaCostControl will look for the offset of the timestamp requested for the reprocessing (if not timestamp requested, it will just see to zero)
  * KafkaCostControl will self-destruct in order for kubernetes to restart it (you may see a restart count increasing)
  * KafkaCostControl kafka stream application will resume from the offset defined by the timestamp you gave

The metric database should be independent. This means it should be able to accept updates. Otherwise, you will need to clean the database yourself before a reprocessing.

=== Using the UI

* Go to the _Others_ tab.
* Choose a date for the start time of the reprocessing (empty means from the beginning of time). You can help yourself with the quick button on top.
* Click on reprocess
* Confirm the reprocessing

==== Using Graphql
[source,graphql]
----
mutation reprocess {
  reprocess(areYouSure: "no", startTime:"2024-01-01T00:00:00Z")
}
----
