kind: Kustomization
resources:
  - ../base
  - telegraf-service-account.yaml

patches:
  - path: deployment.yaml

namespace: kafka

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: telegraf-secret
    envs:
      - .env-telegraf

configMapGenerator:
  - name: telegraf-config
    files:
      - telegraf-config.toml
