---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: telegraf-role
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
---
# Rolebinding for namespace to cluster-admin
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: telegraf-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: telegraf-role
subjects:
- kind: ServiceAccount
  name: telegraf
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: telegraf
