kind: Kustomization
resources:
  - deployment.yaml
  - scraper.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: telegraf-config
    files:
      - telegraf-config.toml
