apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-cost-control-scraper
  labels:
    k8s-app: kafka-cost-control-scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kafka-cost-control-scraper
  template:
    metadata:
      name: kafka-cost-control-scraper
      labels:
        k8s-app: kafka-cost-control-scraper
    spec:
      containers:
        - name: kafka-cost-control-scraper
          image: spoud/kafka-cost-control-scraper:native
          imagePullPolicy: Always
          env:
            - name: KAFKA_SECURITY_PROTOCOL
              value: SASL_SSL
            - name: KAFKA_SASL_MECHANISM
              value: PLAIN
            - name: KAFKA_SASL_JAAS_CONFIG
              value: org.apache.kafka.common.security.plain.PlainLoginModule required username="${CLUSTER_API_KEY}" password="${CLUSTER_API_SECRET}";
            - name: KAFKA_BASIC_AUTH_CREDENTIALS_SOURCE
              value: USER_INFO
            - name: KAFKA_BASIC_AUTH_USER_INFO
              value: ${SCHEMA_REGISTRY_API_KEY}:${SCHEMA_REGISTRY_API_SECRET}
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - secretRef:
                name:
                  kafka-cost-control-scraper-secret

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-cost-control-scraper-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    k8s-app: kafka-cost-control-scraper
