---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: metrics-raw-telegraf-dev
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 3

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kcc-telegraf
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: scram-sha-512
