mutation savePricingRule($request: PricingRuleSaveRequestInput!) {
    savePricingRule(request: $request) {
        creationTime
        metricName
        baseCost
        costFactor
        price
        priceUnit
        multiplier
        multiplierLabel
        validFrom
    }
}

mutation deletePricingRule($request: PricingRuleDeleteRequestInput!) {
    deletePricingRule(request: $request) {
        metricName # response is null!
    }
}

mutation undoPricingRuleChange($request: PricingRuleDeleteRequestInput!) {
    undoPricingRuleChange(request: $request) {
        metricName
        validFrom
    }
}
