apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
spec:
  template:
    spec:
      serviceAccountName: telegraf
      containers:
        - name: telegraf
          env:
            - name: OUTPUT_KAFKA_SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kcc-telegraf
                  key: password
