{{ $rawMetricsTopic := (include "telegrafTopic" .) }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ .Release.Name }}-telegraf
  labels:
    strimzi.io/cluster: {{ .Values.strimzi.clusterName }}
  annotations:
    spoud.io/kcc-context.application: kafka-cost-control
spec:
  authentication:
    type: {{ .Values.strimzi.auth }}
  authorization:
    type: simple
    acls:
      # Example ACL rules for consuming from my-topic using consumer group my-group
      - resource:
          type: topic
          name:  {{ $rawMetricsTopic }}
          patternType: literal
        operations:
          - Describe
          - Read
        host: "*"
      - resource:
          type: group
          name:  "{{ .Release.Name }}-"
          patternType: prefix
        operations:
          - Read
        host: "*"
      # Example ACL rules for producing to topic my-topic
      - resource:
          type: topic
          name:  {{ $rawMetricsTopic }}
          patternType: literal
        operations:
          - Create
          - Describe
          - Write
        host: "*"
