apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-telegraf
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-telegraf
    spec:
      serviceAccountName: {{ .Release.Name }}-telegraf
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-telegraf-config
            defaultMode: 420
            optional: false
        - name: kafka-cluster-ca
          secret:
            secretName: {{ .Values.strimzi.clusterName }}-cluster-ca-cert
      containers:
        - name: telegraf
          image: telegraf:alpine
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          {{ if eq .Values.strimzi.auth "scram-sha-512" }}
          env:
            - name: OUTPUT_KAFKA_SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-telegraf
                  key: password
          {{ end }}
          volumeMounts:
            - name: config
              mountPath: /etc/telegraf
            - name: kafka-cluster-ca
              mountPath: /etc/kafka
              readOnly: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
