name: GitHub Pages + Helm Release and Publish

on:
  push:
    branches: [ master ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # important parameter

      - name: asciidoctor-ghpages
        uses: manoelcampos/asciidoctor-ghpages-action@v2
        with:
          pre_build: |
            mv "docs/" /tmp/source
            mv "helm" /tmp/source/
            #Ignores directories . and .git
            find . -not -path './.git*' -not -name '.' -exec rm -rf {} \; || true
            mv /tmp/source/* .
            # preserve index.yaml
            curl https://spoud.github.io/kafka-cost-control/index.yaml -o index.yaml
            chown -R root:root .
            chmod -R 777 .
            git add .
          pdf_build: true
          asciidoctor_params: -r asciidoctor-diagram
          post_build: 'find . -name "*.svg" | xargs git add -f'
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # important parameter

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: helm
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
